name: "Add new TV channel"
description: "Request addition of a new TV channel to the M3U playlist"
title: "[New channel] Channel name"
labels: ["New channel"]
body:
  - type: markdown
    attributes:
      value: |
        **Please provide the following details about the new TV channel**

  - type: input
    id: channel-name
    attributes:
      label: "TV channel name"
      description: "The official name of the TV channel (e.g., 'Discovery Channel HD')"
      placeholder: "Enter channel name..."
    validations:
      required: true

  - type: input
    id: channel-theme
    attributes:
      label: "TV channel theme"
      description: "Specify the channel's category/theme (e.g., News, Sports, Movies, Kids, Music, etc.)"
      placeholder: "Examples: News, Sports, Entertainment, Documentary..."
    validations:
      required: true

  - type: textarea
    id: regions-languages
    attributes:
      label: "Regions and languages"
      description: "Specify which regions/countries this channel targets and what languages it broadcasts in"
      placeholder: |
        Examples:
        - "International (English)"
        - "Russia (Russian)"
        - "Latin America (Spanish)"
    validations:
      required: true

  - type: textarea
    id: stream-links
    attributes:
      label: "Stream links/playlist blocks"
      description: "Provide one or more working .m3u8 links or ready-made blocks from other M3U playlists (if available)"
      placeholder: |
        Examples:
        - "https://example.com/stream.m3u8"
        - Or paste complete channel block from another playlist:
          "#EXTINF:-1 tvg-id="ChannelID" tvg-name="Channel Name" group-title="Group",Channel Name\nhttp://example.com/stream.m3u8"

  - type: textarea
    id: icon-suggestions
    attributes:
      label: "Icon suggestions"
      description: "You can upload images (drag & drop) or provide links to possible channel logos"
      placeholder: "Paste image URL or attach files here..."
